export const localization = {
  beije: 'Beije',
  user: 'kullanıcı',
  shoopingCart: 'alışveriş sepeti',
  continue: 'devam et',
  products: 'Ürünler',
  packets: 'Paketler',
  allPackets: 'Tüm Paketler',
  wave: 'dalga',
  submit: 'Gönder',
  visa: 'visa',
  masterCart: 'master cart',
  menuItems: {
    allProducts: 'Tüm Ürünler',
    aboutUs: 'Biz Kimiz?',
    donationCulture: 'Bağış Kültürü',
    periodTest: 'Regl Testi!',
    createYourOwnPackage: 'Kendi Paketini Oluştur',
  },
  footer: {
    keepInTouch: 'Arayı açmayalım!',
    keepInTouchDescription:
      'beije’deki yeni ürün ve gelişmeleri sana haber verelim & aylık e-gazetemiz döngü’ye abone ol!',
    policyDescription:
      "Abone olarak, beije KVKK ve Gizlilik Politikası'nı kabul ediyor ve beije'den haber almayı onaylıyorum.",
    emailAddress: 'E-mail Adresin',
    pads: 'beije Ped',
    ped: 'beije Günlük Ped',
    tampon: 'beije Tampon',
    where: 'Biz Kimiz?',
    blog: 'Blog',
    faq: 'Sıkça Sorulan Sorular',
    join: 'Ekibimize Katıl',
    facebook: 'Facebook',
    twitter: 'Twitter',
    instagram: 'Instagram',
    spotify: 'Spotify',
    linkedin: 'LinkedIn',
    kvkk: 'KVKK',
    form: 'KVKK Başvuru Formu',
    membership: 'Üyelik Sözleşmesi',
    policy: 'Gizlilik Politikası',
    cookiePolicy: 'Çerez Politikası',
    test: 'Test Sonuçları',
    rights: '2022 beije. Tüm hakları saklıdır.',
    english: 'EN',
    turkish: 'TR',
  },
};
